version: "3.3"
services:
  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: ./APIGateway/
      dockerfile: Dockerfile
    image: docker-api-gateway-service
    ports:
      - 8989:8989
    networks:
      - network
  discovery-service:
    container_name: discovery-service
    build:
      context: ./DiscoveryService/
      dockerfile: Dockerfile
    image: docker-discovery-service
    ports:
      - 8761:8761
    networks:
      - network
  patient-service:
    container_name: service
    build:
      context: ./AccountService/
      dockerfile: Dockerfile
    image: service
    ports:
      - 8083:8083
    networks:
      - network
networks:
  network:
    name: network
    driver: bridge