version: "3.3"
services:
  discovery-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-discovery-service
    ports:
      - 8761:8761
    networks:
      - network
    restart: always
networks:
  restaurant:
    name: network
    driver: bridge