version: "3.3"
services:
  service:
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    image: service
    ports:
      - 8083:8083
    networks:
      - network
    restart: always
networks:
  network:
    name: network
    driver: bridge